spring:
  datasource:
    url: jdbc:mariadb://localhost:3313/lunch?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: lunch
    password: lunch1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6380
      password: sequence
      timeout: 3s

server:
  port: 8080

jwt:
  secret:
    key: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="

